name: sample-workflow
on: [push]
jobs:
  explore-first-github-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this job was automatically triggered by a ${{ github.event_name}} event."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "the ${{ github.repository}} repo has been cloned to the runner"
      - name: list files in the repo
        run: | 
          ls ${{ github.workspace}}
      - run: echo "this job's status is ${{ job.status}}"
